name: Mirroring
on:
  push:
  delete:
  workflow_dispatch:
jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab-ssh.univ-lille.fr >> ~/.ssh/known_hosts

    - name: Push to GitLab
      run: |
        git remote add gitlab git@gitlab-ssh.univ-lille.fr:yann.renard.etu/dev-oo.git
        git push gitlab main